services:
  - type: static_site
    name: fest-flutter-app
    buildCommand: bash ./build.sh
    staticPublishPath: ./build/web
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
